<a href="https://colab.research.google.com/github/PytonDS/DS-Bootcamp-Udemy-KrakowiakP/blob/main/Numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [261]:
import numpy as np
np.__version__

'1.21.6'

In [ ]:
dir(np)

In [ ]:
help(np.array)

### TABELE / WYMIARY

In [264]:
x = np.array([1, 2, 3])
x.ndim

1

In [265]:
x = np.array([[1, 2, 3], [2, 3, 15], [3, 3, 3], [8, 79, 12]])
print('x shape -', x.shape)
print('x size -', x.size)
print('x dimmensions -', x.ndim)
print('x type -', x.dtype)
print('\n', x)

x shape - (4, 3)
x size - 12
x dimmensions - 2
x type - int64

 [[ 1  2  3]
 [ 2  3 15]
 [ 3  3  3]
 [ 8 79 12]]


In [266]:
x = np.array(
              [[[1, 2, 3], 
               [2, 3, 15]],
               
              [[3, 3, 3], 
               [8, 79, 12]]]
              )
print('x shape -', x.shape)
print('x size -', x.size)
print('x dimmensions -', x.ndim)
print('x type -', x.dtype)
print('\n', x)

x shape - (2, 2, 3)
x size - 12
x dimmensions - 3
x type - int64

 [[[ 1  2  3]
  [ 2  3 15]]

 [[ 3  3  3]
  [ 8 79 12]]]


### TYPY DANYCH

In [267]:
A = np.array([1, 2, 3], dtype='int16')
A.dtype

dtype('int16')

In [268]:
X = np.array([[15,5,5],[8,12,5],[4,4,4],[12.23,12.5,12.6]])
X.round(0).astype('int')

array([[15,  5,  5],
       [ 8, 12,  5],
       [ 4,  4,  4],
       [12, 12, 13]])

In [269]:
A = np.array([False, False, True])
A.dtype

dtype('bool')

### TWORZENIE TABLIC

In [270]:
np.zeros(shape = (4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [271]:
np.ones(shape = (5, 5), dtype = 'int8')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [272]:
np.full(shape=(3, 3), fill_value=4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [273]:
x = np.arange(10)

In [274]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [275]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [276]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

linspace

In [277]:
np.linspace(start=0, stop=1, num=101)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [278]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [279]:
print(A.reshape((3, 5)))

print('\n', A.reshape((5, -1, 3)))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

 [[[ 0  1  2]]

 [[ 3  4  5]]

 [[ 6  7  8]]

 [[ 9 10 11]]

 [[12 13 14]]]


### OPERACJE NA TABLICACH

In [280]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [281]:
A + B

array([6, 0, 7, 4])

In [282]:
A - B

array([0, 2, 1, 0])

In [283]:
A * B

array([ 9, -1, 12,  4])

In [284]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [285]:
A + 3

array([6, 4, 7, 5])

In [286]:
A * 2

array([6, 2, 8, 4])

In [287]:
np.absolute(B)

array([3, 1, 3, 2])

In [288]:
A + 3*B

array([12, -2, 13,  8])

Wbudowane metody

In [289]:
np.add(A, B)

array([6, 0, 7, 4])

In [290]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [291]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [292]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

-------------------------Mnożenie macierzowe-----------------------------



In [293]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])

print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [294]:
print(X * Y, '\n')
print(np.multiply(A, B))

[[6 0]
 [2 0]] 

[ 9 -1 12  4]


In [295]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [296]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [297]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [298]:
Y @ X

array([[ 6, 18],
       [-5, -3]])

### GENEROWANIE LICZB PSEUDOLOSOWYCH

In [299]:
np.random.seed(0)

In [300]:
np.random.randn() #losowy rozkład normalny standardowy

1.764052345967664

In [301]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [302]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [303]:
np.random.rand() #losowy rozkład jednostajny [0, 1)

0.1965823616800535

In [304]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [305]:
np.random.rand(10, 4)

array([[0.03918779, 0.28280696, 0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318, 0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145, 0.26538949, 0.52324805],
       [0.09394051, 0.5759465 , 0.9292962 , 0.31856895],
       [0.66741038, 0.13179786, 0.7163272 , 0.28940609],
       [0.18319136, 0.58651293, 0.02010755, 0.82894003],
       [0.00469548, 0.67781654, 0.27000797, 0.73519402],
       [0.96218855, 0.24875314, 0.57615733, 0.59204193],
       [0.57225191, 0.22308163, 0.95274901, 0.44712538],
       [0.84640867, 0.69947928, 0.29743695, 0.81379782]])

In [306]:
np.random.randint(2) #liczby losowe z przedziału [0, x)

1

In [307]:
np.random.randint(10)

8

In [308]:
np.random.randint(low=10, high=101) # [10, 100], losowa liczba dwucyfrowa

26

In [309]:
np.random.randint(low=10, high=101, size=(10,4))

array([[34, 39, 31, 35],
       [90, 70, 71, 93],
       [43, 42, 80, 95],
       [41, 23, 81, 66],
       [34, 89, 51, 28],
       [50, 64, 89, 21],
       [48, 11, 54, 98],
       [34, 77, 92, 13],
       [86, 45, 96, 71],
       [79, 97, 53, 42]])

In [310]:
np.random.choice([4, 2, 1, 3]) #losowy element ze zbioru

3

In [311]:
np.random.choice(['python', 'Java', 'SQL'])

'python'

In [312]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [313]:
np.random.shuffle(data) # Zmiana zachodzi od razu // Inaczej w pandas (Inplace=True)
data

array([1, 2, 0, 7, 9, 8, 5, 3, 6, 4])

### PODSTAWOWE FUNKCJE

In [314]:
np.exp(1) # Wartość exponentalna e^1 = e Eulera

2.718281828459045

In [315]:
np.sqrt(9)

3.0

In [316]:
print(np.all([2, 3, 1]))
print(np.all([2, 3, 1, 0]))

True
False


In [317]:
print(np.any([2, 3, 1]))
print(np.any([2, 3, 1, 0]))
print(np.any([0, 0, 0]))

True
True
False


In [318]:
np.array([0, 0, 1]) == 0

array([ True,  True, False])

In [319]:
np.array([[0, 0, 0], [0, 0, 0], [0, 0, 1]]) == np.zeros(shape=(3, 3))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False]])

In [320]:
print(bool(0))
print(bool(1.7))

False
True


In [321]:
A = np.random.rand(5)
A

array([0.50831545, 0.16684751, 0.77905102, 0.8649333 , 0.41139672])

In [322]:
print('matrix -', A)
print('argmax -', np.argmax(A))
print('matrix[4] -', A[4])
print('A[argmax] -', A[np.argmax(A)])

matrix - [0.50831545 0.16684751 0.77905102 0.8649333  0.41139672]
argmax - 3
matrix[4] - 0.41139672375545455
A[argmax] - 0.8649332956024927


In [323]:
np.argmin(A)

1

In [324]:
A[np.argsort(A)]

array([0.16684751, 0.41139672, 0.50831545, 0.77905102, 0.8649333 ])

In [325]:
np.max(A)

0.8649332956024927

In [326]:
np.min(A)

0.16684751304849965

In [327]:
np.mean(A)

0.5461088001188747

In [328]:
np.median(A)

0.5083154485788909

In [329]:
np.std(A) # Odchylenie standardowe

0.2527156272771559

### INDEKSOWANIE I WYCINANIE TABLIC

In [330]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [331]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [332]:
A[2]

2

In [333]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [334]:
A[:2]

array([0, 1])

In [335]:
A[[0, 2]]

array([0, 2])

In [336]:
A[-1]

19

In [337]:
A[10:15]

array([10, 11, 12, 13, 14])

In [338]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [339]:
A[1]

array([5, 6, 7, 8, 9])

In [340]:
A[:, 2]

array([ 2,  7, 12, 17])

In [341]:
A[:, -1]

array([ 4,  9, 14, 19])

In [342]:
A[1, 1]

6

In [343]:
A[[1,2], 1:4] # A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [344]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### ITEROWANIE PO TABLICACH

In [345]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [346]:
for row in A:
  print(row[1])

1
6
11
16


In [347]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [348]:
counter = 0

for item in A.flat: # Iterowanie po każdym elemencie
  print(item)
  counter += item

print("sprawdzenie - counter: %d, A.sum(): %d" % (counter, A.sum()))

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19
sprawdzenie - counter: 197, A.sum(): 197


Zmiana rozmiaru tablic

In [349]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [350]:
A.shape

(4, 5)

In [351]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [352]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [354]:
A.T # A.transpose()

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [360]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Maski logiczne

In [365]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [366]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [368]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [369]:
A[A > -5 and A < 5]

ValueError: ignored

In [370]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [371]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [372]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [373]:
A[np.bitwise_or(A < -5, A > 5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])