<a href="https://colab.research.google.com/github/PytonDS/DS-Bootcamp-Udemy-KrakowiakP/blob/main/NumPy_03_Funkcje_statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
price = np.array([[12.40, 12.80, 11.90, 12.60, 1000],
                  [12.50, 13.00, 11.70, 12.20, 2000],
                   [12.20, 13.40, 12.20, 13.20, 1500]])

print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


In [21]:
price.sum(axis=0)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [11]:
np.sum(price)

4650.1

In [57]:
np.set_printoptions(precision=4, suppress=True)
price.mean(axis=0)

array([  12.3667,   13.0667,   11.9333,   12.6667, 1500.    ])

In [58]:
np.min(price, axis=0)

array([  12.2,   12.8,   11.7,   12.2, 1000. ])

In [59]:
np.max(price, axis=0)

array([  12.5,   13.4,   12.2,   13.2, 2000. ])

In [60]:
np.median(price)

12.6

In [61]:
price.median() # !!!!

AttributeError: ignored

In [62]:
np.std(price, axis=0)

array([  0.1247,   0.2494,   0.2055,   0.411 , 408.2483])

In [63]:
price.std(axis=0)

array([  0.1247,   0.2494,   0.2055,   0.411 , 408.2483])

In [64]:
np.var(price, axis=0)

array([     0.0156,      0.0622,      0.0422,      0.1689, 166666.6667])

In [65]:
price.var(axis=0)

array([     0.0156,      0.0622,      0.0422,      0.1689, 166666.6667])