<a href="https://colab.research.google.com/github/PytonDS/DS-Bootcamp-Udemy-KrakowiakP/blob/main/NymPy_02_Algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Norma wektora, długość wektora w R2

In [2]:
v1 = np.array([0, 4])
v1

array([0, 4])

In [7]:
np.linalg.norm(v1) # norma wektora v1

4.0

Norma euklidesowa w Rn

In [10]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2) # norma euklidesowa w R3 (współrzędne w trzech wymiarach)

19.209372712298546

Odległość dwóch punktów na płaszczyźnie

In [9]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p - q)

5.0

Odległość dwóch punktów w przestrzeni Rn

In [11]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p - q)

5.0990195135927845

### WYZNACZNIK MACIERZY

In [13]:
A = np.array([[2, 4], [-1, 3]])
np.linalg.det(A)

9.999999999999998

### ŚLAD MACIERZY

In [14]:
A = np.array([[2, 4], [-1, 3]])
np.trace(A)

5

### MACIERZ JEDNOSTKOWA

In [17]:
np.eye(5, dtype='int8')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

### MACIERZ ODWROTNA

In [19]:
A = np.array([[2, 4], [-1, 3]])
np.linalg.inv(A)

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [20]:
B = np.linalg.inv(A)

In [23]:
np.set_printoptions(precision=4, suppress=True)

np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [24]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

### MACIERZ TRANSPONOWANA

In [25]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [27]:
A.T

array([[ 2, -1],
       [ 4,  3]])

In [28]:
A

array([[ 2,  4],
       [-1,  3]])

### ROZWIĄZYWANIE UKŁADÓW RÓWNAŃ

Układ równań:

2x + 4y = 10

x - y = -1

In [35]:
A = np.array([[2, 4], [1, -1]]) # Macierz współczynników
A

array([[ 2,  4],
       [ 1, -1]])

In [36]:
B = np.array([[10], [-1]]) # MWektor wyrazów wolnych
B

array([[10],
       [-1]])

In [38]:
A_inv = np.linalg.inv(A) # Macierz wynikowa X (x, y) - czyli A_inv * B
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])